# Polars Series

In [1]:
import polars as pl
path_data = '../../../assets/data/'

While there are many kinds of collections in Python, we will work primarily with Polars Series in this class. We've already seen that `pl.Series` can be used to create a Polars Series of numbers.

A Polars Series can also contain strings or other types of values, but a single Polars Series can only contain a single kind of data. (It usually doesn't make sense to group together unlike data anyway.)  For example:

In [2]:
english_parts_of_speech = pl.Series("english_parts_of_speech", ["noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection"])
english_parts_of_speech

shape: (8,)
Series: 'english_parts_of_speech' [str]
[
	"noun"
	"pronoun"
	"verb"
	"adverb"
	"adjective"
	"conjunction"
	"preposition"
	"interjection"
]

Returning to the temperature data, we create a Polars Series of average daily [high temperatures](http://berkeleyearth.lbl.gov/auto/Regional/TMAX/Text/global-land-TMAX-Trend.txt) for the decades surrounding 1850, 1900, 1950, and 2000.

In [3]:
baseline_high = 14.48
highs = pl.Series("highs", [baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684])
highs

shape: (4,)
Series: 'highs' [f64]
[
	13.6
	14.387
	14.585
	15.164
]

Polars Series can be used in arithmetic expressions to compute over their contents. When a Polars Series is combined with a single number, that number is combined with each element of the Series. Therefore, we can convert all of these temperatures to Fahrenheit by writing the familiar conversion formula.

In [4]:
(9/5) * highs + 32

shape: (4,)
Series: 'highs' [f64]
[
	56.48
	57.8966
	58.253
	59.2952
]

![Visual representation of Polars Series arithmetic. (9/5) times the Polars Series highs (13.6, 14.387, 14.585, 15.164) plus 32 equals (9/5) times 13.6 + 32 in the first slot of the resulting Polars Series, followed by (9/5) times 14.387 plus 32 in the second slot of the Polars Series, and so on. Finally on the right hand side of the image, a Polars Series is shown with the final answers (56.48, 57.8966, 58.253, 59.2952).](../../../images/array_arithmetic.png)

Polars Series also have *methods*, which are functions that operate on the Series values. The `mean` of a collection of numbers is its average value: the sum divided by the length. Each pair of parentheses in the examples below is part of a call expression; it's calling a function with no arguments to perform a computation on the Polars Series called `highs`.

In [5]:
highs.len()

4

In [6]:
highs.sum()

57.736000000000004

In [7]:
highs.mean()

14.434000000000001

## Functions on Polars Series
A Polars Series has methods for manipulating its values. Call a method on the Series, as in `highs.diff()`.

For example, the `diff` method computes the difference between each adjacent pair of elements in a Polars Series. The first element is null. Each later element is that element minus the one before it.

In [8]:
highs.diff()

shape: (4,)
Series: 'highs' [f64]
[
	null
	0.787
	0.198
	0.579
]

The [Polars Series reference](https://docs.pola.rs/api/python/stable/reference/series/index.html) lists these methods exhaustively, but only a small subset are used commonly for data processing applications. String methods are called on `str`, as in `s.str.to_lowercase()`. Learning this vocabulary is an important part of learning the Python language, so refer back to this list often as you work through examples and problems.

However, you **don't need to memorize these**.  Use this as a reference.

Each of these methods returns a single value.

| **Method**       | Description                                                          |
|--------------------|----------------------------------------------------------------------|
| `s.product()`          | Multiply all elements together                                       |
| `s.sum()`           | Add all elements together                                            |
| `(s != 0).all()`           | Test whether all elements are true values (non-zero numbers are true)|
| `(s != 0).any()`           | Test whether any elements are true values (non-zero numbers are true)|
| `(s != 0).sum()` | Count the number of non-zero elements                                |

Each of these methods returns a Polars Series of values.

| **Method**       | Description                                                          |
|--------------------|----------------------------------------------------------------------|
| `s.diff()`          | Difference between adjacent elements. The first element is null.     |
| `s.round()`         | Round each number to the nearest integer (whole number)              |
| `s.cum_prod()`       | A cumulative product: for each element, multiply all elements so far |
| `s.cum_sum()`        | A cumulative sum: for each element, add all elements so far          |
| `s.exp()`           | Exponentiate each element                                            |
| `s.log()`           | Take the natural logarithm of each element                           |
| `s.sqrt()`          | Take the square root of each element                                 |
| `s.sort()`          | Sort the elements                                                    |

Each of these string methods takes a Polars Series of strings and returns a Polars Series.

| **Method**        | **Description**                                              |
|---------------------|--------------------------------------------------------------|
| `s.str.to_lowercase()`     | Lowercase each element                                       |
| `s.str.to_uppercase()`     | Uppercase each element                                       |
| `s.str.strip_chars()`     | Remove spaces at the beginning or end of each element        |
| `s.str.contains(r"^\p{Alphabetic}+$")`   | Whether each element is only letters (no numbers or symbols) |
| `s.str.contains(r"^\d+$")` | Whether each element is only numeric (no letters)            |

Each of these string methods takes a search string as well; each returns a Polars Series.

| **Method**         | **Description**                                                                  |
|----------------------|----------------------------------------------------------------------------------|
| `s.str.count_matches(substr, literal=True)`      | Count the number of times a search string appears among the elements of a Polars Series |
| `s.str.find(substr, literal=True)`       | The position within each element that a search string is found first. A missing search is null. |
|  | The last position of a search string has no Polars Series method. |
| `s.str.starts_with(substr)` | Whether each element starts with the search string                               |